### ISSUE TITLE
Handle queuing

### ISSUE THREAD

**Issue by dotgrid** [fidecastro/ComfyUI-serverless#1]
If this is to become the [official API interface](https://github.com/comfyanonymous/ComfyUI/pull/1216), could it be extended to handle the queuing of tasks?

Kudos to you for building this, it's brilliant! I've been using ComfyUI in this manner, and I ended up having to roll my own similar wrapper to the ComfyUI websocket interface (but in Ruby).

**Comment by fidecastro** [comment]
Hey! Wow, sorry for the uber late reply; wasn't paying attention to the repo. Glad you liked it @dotgrid!

Technically it uses Comfy queuing as a way to request the images. I haven't tested it, but I believe that what you're asking for can be done by simply switching the code to async and making any necessary adaptations.
