### ISSUE TITLE
batch counts

### ISSUE THREAD

**Issue by p0mad** [fidecastro/ComfyUI-serverless#3]
@fidecastro Is there a way to run the same API for multiple queue (batch counts)?
I have a sequence image loader and also sequence image save. So now i want to run the whole folder with a single API call!

any idea would be much appritiated!
Thanks

**Comment by fidecastro** [comment]
@p0mad so sorry for the late reply. I'm now paying attention to the repo so will respond faster next time!

There is, but the easiest way to go about this would be to control this via the API json itself. To the extent there are ways to programmatically do that in it (ie empty latent image node having batch count, for instance), I'd prefer doing it there as opposed to changing it in this repository. Let me know what you think.
