### ISSUE TITLE
"image to video" and "video to video" generation

### ISSUE THREAD

**Issue by darkcurrent** [fidecastro/ComfyUI-serverless#5]
Hello,

First of all thank your for this really useful code...

Some workflows is based on "image to video" and "video to video" generation. Is it possible to adding this features? If so are you planning to add this?

**Comment by fidecastro** [comment]
That would be awesome. I haven't yet seen a ComfyUI workflow for that, but am really interested in making it work for it. Can you share one of these Comfy workflows with me @darkcurrent?

**Comment by darkcurrent** [comment]
Actually, I do all my work using the diffusers library, but due to the complexity of the configurations, I came up with the idea of using ComfyUI to do both the testing and development process in a single environment. Being able to use the whole workflow as json with the API provides great convenience.

I haven't done any work yet, but I know that there are works developed using ComfyUI on this subject. Especially AnimateDiff is very important, because it creates really incredible videos in a consistent way.

https://github.com/ArtVentureX/comfyui-animatediff

**Comment by fidecastro** [comment]
Thanks for sharing this! I didn't pay enough attention to AnimateDiff and will check it out
