### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Niutonian** [fidecastro/ComfyUI-serverless#7]
Hello is there a tutorial on how to use your repo, 
I found it while looking for exotic ways to run ComfyUI, 
but I do not understand how it works. 

Thank you in advance

**Comment by fidecastro** [comment]
Hey @Niutonian -- it introduces a class called ComfyConnector that deals with starting and running ComfyUI in the backend.

To make it work, you basically just need to make sure the API_COMMAND_LINE variable is set to the correct path to run your ComfyUI install. Once that's done, you'll be able to launch ComfyUI by just creating an instance of ComfyConnector, say, by adding the following lines to your python code (assuming you cloned this repository and are working on the base folder of it):

```
from comfy_serverless import ComfyConnector
comfy_connector = ComfyConnector()

```

Once you do that, ComfyUI will start, and the comfy_connector instance will be a singleton of the ComfyConnector class. That means that wherever you invoke it in your code, you'll get the same ComfyUI session you were working with.

The generally useful methods in the ComfyConnector class should be the following:

- generate_images: This is the main reason why I created this repository. This method is used to pass to ComfyUI the workflow_api.json that can be exported from ComfyUI on Developer mode. Its output is a list of the Image objects generated by ComfyUI (note that the images you create should also be present in the ComfyUI output folder as usual). Also, VERY IMPORTANT: workflow_api.json must contain one, and only one, SaveImage node for the method to work.

- upload_image: This method is used to upload an image to the API server for use in img2img, controlnet, etc.

- replace_key_value: This method can be used to edit the payload of a prompt. It might be helpful if you are building a system that would require some parameters of the API to be changed programmatically.

Let me know if that resolves your question!
