### ISSUE TITLE
TypeError in INITIAL_PORT

### ISSUE THREAD

**Issue by mariokhz** [fidecastro/ComfyUI-serverless#8]
INITIAL_PORT = int(os.getenv('INITIAL_PORT')) # Initial port to use when starting the API server; may be changed if the port is already in use
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by mariokhz** [comment]
I just replaced all the os.getenv() with te actual values I wanted and it worked.

**Comment by 0q2** [comment]
But why?

**Comment by 0q2** [comment]
I figured it out. If you have ZSH as your shell you have to run
`. ./set_env_variables.sh`
to correctly set your env variables before you run the python REPL.

**Comment by mariokhz** [comment]
> I figured it out. If you have ZSH as your shell you have to run `. ./set_env_variables.sh` to correctly set your env variables before you run the python REPL.

I was using Windows CMD, and running the .sh didn't work at all, as I always had some issue around the env variables
